<!-- Notification Page showing that the user account has been successfully added -->
<div class="row">
	<div class="small-12 large-centered columns">
		<div class="panel">
			<h1 class="text-center"><?php echo $data[0]?></h1>
			<p class="text-center">Thank you for signing up with Procipe!</p>
			<p class="text-center">Please <a href="?rq=lo" class="small button">Log In</a> to get cookin'.</p>
		</div>
	</div>
</div>