<!DOCTYPE html>
<!--[if IE 8]>		<html class="no-js lt-ie9" lang="en">  <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title><?php echo $page_title; ?></title>
	<link rel="stylesheet" type="text/css" href="../foundation-4.3.1/css/normalize.css">
	<link rel="stylesheet" type="text/css" href="../foundation-4.3.1/css/foundation.css" />
	<script src="foundation-4.3.1/js/vendor/custom.modernizr.js"></script>
</head>
<header class="full-width header-area">
	<div class="row">
		<div class="small-12 columns">
			<a href="index.php"><img src="assets/procipe_logo150x70.png"></a>
		</div>
	</div>
</header>
<div class="full-width navigation-area">
    <div class="row">
        <div class="large-12 columns">
            <nav class="top-bar"></nav>
        </div>
    </div>
</div>
<body>
