<!DOCTYPE html>
<!--[if IE 8]>		<html class="no-js lt-ie9" lang="en">  <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>Procipe Free Recipe Search</title>
	<link rel="stylesheet" type="text/css" href="../foundation-4.3.1/css/normalize.css">
	<link rel="stylesheet" type="text/css" href="../foundation-4.3.1/css/foundation.css" />
	<link rel="stylesheet" type="text/css" href="../foundation-4.3.1/css/style.css" />
	<script src="foundation-4.3.1/js/vendor/custom.modernizr.js"></script>
</head>
<header class="full-width header-area">
	<div class="row">
		<div class="small-8 columns">
			<a href="index.php"><img src="assets/procipe_logo150x50.png"></a>
		</div>
		<!--<div class="small-3 columns right">
			<p>Welcome back, Jimmy</p>
		</div> -->
	</div>
</header>
<div class="full-width navigation-area">
    <div class="row">
        <div class="large-12 columns">
            <nav class="top-bar">
            	<ul class="title-area">
            		<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
            	</ul>
            	<section class="top-bar-section">
            		<ul class="left">
            			<li class="divider"></li>
            			<li><a href="index.php">Log In</a></li>
            			<li class="divider"></li>
            			<li><a href="?na=new">Sign Up</a></li>
            		</ul>
            	</section>
            </nav>
        </div>
    </div>
</div>
<body>
