<!DOCTYPE html>
<!--[if IE 8]>		<html class="no-js lt-ie9" lang="en">  <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title><?php echo $page_title; ?></title>
	<link rel="stylesheet" type="text/css" href="../foundation-4.3.1/css/normalize.css">
	<link rel="stylesheet" type="text/css" href="../foundation-4.3.1/css/foundation.css" />
	<script src="foundation-4.3.1/js/vendor/custom.modernizr.js"></script>
</head>
<body>
