<?php
$page_title = "Procipe Login";
?>
<h1>Procipe</h1>
<p>Powered by the Yummly API</p>
<p>Procipe is a FREE recipe search app that lets you find over 170,000 great recipes!  Powered by the Yummly API you can search &amp; view recipes, save your favorite recipes and create shopping lists from those recipes.  Free to sign up, give it a try today!</p>
<form action="" method="post">
	<label for="username">Username:</label><br/>
		<input type="text" name="username" id="username" maxlength="20"/><br/>
	<label for="password">Password:</label></br>
		<input type = "password" name="password" id="password" /><br/>
	<input type="submit" name="submit" value="Log In" />
<p>Don't have an account?&nbsp;<a href="?na=new">Sign Up</a>&nbsp;for free!</p>
</form>
