<div class="row">
	<div class="small-7 large-centered columns">
		<div class="panel">
			<h1>Create Your Procipe Account</h1>
			<h6 class="subhead">Please fill out the form to create a Procipe account.</h6>
			<form action="" method="post">
				<div class="row">
					<div class="large-9 columns">
						<p>Usernames must be at least 5 characters and include at least 1 upper case letter and 1 number.</p>
						<label for="new_username">Username:</label>
						<input type="text" name="new_username" id="new_username" maxlength="20" placeholder="Choose a username" /><br/>
					</div>
				</div>
				<div class="row">
					<div class="large-9 columns">
						<p>Passwords must be at least 6 characters and include at least 1 upper case letter, 1 number and a special character.</p>
						<label for="new_password">Password:</label>
						<input type="password" name="new_password" id="new_password" maxlength="15" placeholder="Choose a password" /><br/>
					</div>
				</div>
				<div class="row">
					<div class="large-9 columns">
						<p>Please provide some information about you below.</p>
						<label for="first_name">First:</label>
						<input type="text" name="first_name" id="first_name" maxlength="20" placeholder="Please enter your first name"/><br/>
						<label for="last_name">Last:</label>
						<input type="text" name="last_name" id="last_name" maxlength="20" placeholder="Please enter your last name"/><br/>
						<label for="email">Email:</label>
						<input type="text" name="email" id="email" maxlength="50" placeholder="Please enter your email address"/><br/>
						<input type="submit" name="submit_new" value="Create Account" class="button small"/>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>